### ISSUE TITLE
项目不完整，文件缺失很多

### ISSUE THREAD

**Issue by torlinpeng** [leeggco/g6-editor-demo#1]
差评

**Comment by leeggco** [comment]
缺失了什么文件呢，有安装依赖了吗

**Comment by wangmh2** [comment]
你自己的问题吧，我能直接跑起来

**Comment by wangmh2** [comment]
> 缺失了什么文件呢，有安装依赖了吗

想问一下G6编辑器能不能把流程图输出成json呢？

**Comment by leeggco** [comment]
> 想问一下G6编辑器能不能把流程图输出成json呢？

可以的，net.save() 就可以输出json。

**Comment by wangmh2** [comment]
> > 想问一下G6编辑器能不能把流程图输出成json呢？
> 
> 可以的，net.save() 就可以输出json。

你好，请问能加下QQ吗？我对前端不太熟悉，能否请教一下你？我的QQ1103574375

**Comment by leeggco** [comment]
> > > 想问一下G6编辑器能不能把流程图输出成json呢？
> > 
> > 
> > 可以的，net.save() 就可以输出json。
> 
> 你好，请问能加下QQ吗？我对前端不太熟悉，能否请教一下你？我的QQ1103574375

抱歉，不太方便呢，你可以在这里描述你的问题，我尽量帮助你咯。

**Comment by wangmh2** [comment]
> > > > 想问一下G6编辑器能不能把流程图输出成json呢？
> > > 
> > > 
> > > 可以的，net.save() 就可以输出json。
> > 
> > 
> > 你好，请问能加下QQ吗？我对前端不太熟悉，能否请教一下你？我的QQ1103574375
> 
> 抱歉，不太方便呢，你可以在这里描述你的问题，我尽量帮助你咯。

我需要将后台传来的json数据渲染成流程图，G6中该怎么做呢？

**Comment by leeggco** [comment]
> > > > > 想问一下G6编辑器能不能把流程图输出成json呢？
> > > > 
> > > > 
> > > > 可以的，net.save() 就可以输出json。
> > > 
> > > 
> > > 你好，请问能加下QQ吗？我对前端不太熟悉，能否请教一下你？我的QQ1103574375
> > 
> > 
> > 抱歉，不太方便呢，你可以在这里描述你的问题，我尽量帮助你咯。
> 
> 我需要将后台传来的json数据渲染成流程图，G6中该怎么做呢？

可以参考这个示例： https://antv.alipay.com/zh-cn/g6/3.x/demo/flow/dagre.html
一般情况下可以使用模拟数据先绘制出流程图的样式，再对接后台的数据。

**Comment by wangmh2** [comment]
> > > > > > 想问一下G6编辑器能不能把流程图输出成json呢？
> > > > > 
> > > > > 
> > > > > 可以的，net.save() 就可以输出json。
> > > > 
> > > > 
> > > > 你好，请问能加下QQ吗？我对前端不太熟悉，能否请教一下你？我的QQ1103574375
> > > 
> > > 
> > > 抱歉，不太方便呢，你可以在这里描述你的问题，我尽量帮助你咯。
> > 
> > 
> > 我需要将后台传来的json数据渲染成流程图，G6中该怎么做呢？
> 
> 可以参考这个示例： https://antv.alipay.com/zh-cn/g6/3.x/demo/flow/dagre.html
> 一般情况下可以使用模拟数据先绘制出流程图的样式，再对接后台的数据。

好的，谢谢

**Comment by wangmh2** [comment]
你好，我遇到一个问题能否请教你一下？我从数据库中取出流程图数据后使用read()方法对数据进行渲染，节点能够显示，但是连线不能显示，并且报了一个错误TypeError: Cannot read property 'isVisible' of undefined，这个isVisible我不知道是在哪里定义出来的，我自己百分之百没有定义

**Comment by wangmh2** [comment]
> 你好，我遇到一个问题能否请教你一下？我从数据库中取出流程图数据后使用read()方法对数据进行渲染，节点能够显示，但是连线不能显示，并且报了一个错误TypeError: Cannot read property 'isVisible' of undefined，这个isVisible我不知道是在哪里定义出来的，我自己百分之百没有定义

已经解决了，原因是我之前保存元数据到数据库的时候把边里的source和target替换成节点的label了，数据格式与文档中的不同，所以渲染的时候报错

**Comment by leeggco** [comment]
closed
